import "dotenv/config";
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const descs: { title: string; desc: string }[] = [
  // Frizideri (already done above)
  // Checkout
  { title: "Standard kasa pult", desc: "Provjereno rješenje za svakodnevni rad, ergonomski raspored i trajna konstrukcija." },
  { title: "Standard Plus pult", desc: "Nadograđen standard sa dodatnim radnim površinama i odlaganjem." },
  { title: "Premium kasa pult", desc: "Premium dizajn i materijali za reprezentativnu zonu naplate." },
  { title: "Premium Light pult", desc: "Premium estetika u pristupačnijoj, lakšoj konfiguraciji." },
  { title: "Convenience kasa pult", desc: "Kompaktni pult za manje formate i brzu naplatu." },
  { title: "Lime Light pult", desc: "Vizualno atraktivan pult sa osvjetljenom prednjom stranom." },
  { title: "Lime Line pult", desc: "Minimalistički pult sa čistim linijama za moderan izgled." },
  { title: "Modularni kasa pultovi", desc: "Modularni sistem koji se prilagođava različitim formatima naplate." },
  { title: "Mini kase", desc: "Kompaktne kase za male objekte i convenience formate." },
  { title: "Impulsni kasa pult", desc: "Pult sa integriranom impulsnom zonom za dodatan prihod." },
  { title: "Sklopivi kasa pult", desc: "Sklopivi pult koji se brzo aktivira ili skloni po potrebi." },
  { title: "SmartPos self-checkout", desc: "SmartPos sa Netris integracijom — kompaktno, brzo i intuitivno." },
  { title: "SmartPos Light", desc: "Kompaktna card-only varijanta SmartPos za manji promet." },
  { title: "Netris self-checkout", desc: "Netris kompaktni self-checkout sa kartičnim plaćanjem." },
  { title: "MainBox kiosk", desc: "Informacijski kiosk i samouslužni terminal za veće objekte." },
  { title: "Kiosk za narudžbe", desc: "Touchscreen kiosk za narudžbe u QSR i ugostiteljskim objektima." },
  { title: "FoodBox samousluga", desc: "Samouslužni FoodBox za kupovinu gotove hrane i napitaka." },
  { title: "FoodBox za prodavnice", desc: "FoodBox kiosk za prodavnice sa integrisanim asortimanom." },
  { title: "RVM reciklaža ambalaže", desc: "Reverse vending machine za povrat i reciklažu ambalaže." },
  // Policni
  { title: "Cjenovne šine", desc: "Noseće šine za jasan i uredan prikaz cijena na policama." },
  { title: "Držači cijena za kukice", desc: "Držači cjenovnih oznaka za prodaju na kukicama." },
  { title: "Držači za ESL cjenovnike", desc: "Nosači i šine za elektronske cjenovnike sa centralnim ažuriranjem." },
  { title: "Papirne cjenovne trake", desc: "Nosači papirnih cjenovnih traka za razne tipove polica." },
  { title: "Automatsko poravnavanje (pusheri)", desc: "Automatski pusheri koji drže proizvode poravnate na polici." },
  { title: "Ručno poravnavanje (faceri)", desc: "Ručni faceri za brzo i uredno poravnavanje asortimana." },
  { title: "Pregrade za police", desc: "Razdjelnici koji odvajaju i organizuju police po kategorijama." },
  { title: "Svježi proizvodi — ambient display", desc: "FreshCase rješenja za izlaganje svježeg programa bez pakovanja." },
  { title: "Svježi proizvodi — hladni raspon (coolers)", desc: "Rashladni cooler sustavi za svjež program na polici." },
  { title: "Posude za doziranje", desc: "Dozatori za prodaju robe na kg bez pakovanja." },
  { title: "Gravitacione posude za bulk", desc: "Gravitacione posude za prodaju rasute robe." },
  { title: "Posude za tečnost", desc: "Posude sa slavinom za doziranje tečnih proizvoda." },
  { title: "Samostojeći display elementi", desc: "Samostojeći displeji za impulsne i promotivne zone." },
  { title: "Unakrsno izlaganje", desc: "Sistemi za cross-merchandising na gondolama i krajevima polica." },
  { title: "Nadznaci za prolaze i odjeljenja", desc: "Nadznaci koji vode kupca kroz prodajni prostor." },
  { title: "Promocija na ivici police", desc: "Shelf-edge rješenja za isticanje promotivnih cijena." },
  { title: "Ramovi i stalci za komunikaciju", desc: "A4/A3 ramovi i stalci za komunikaciju s kupcem." },
  { title: "Tacne za police", desc: "Dekorativne tacne za uredan i pregledan prikaz na polici." },
  { title: "Zaštita od krađe", desc: "Anti-theft sistemima koji štite vrijedan asortiman." },
  { title: "Rasvjeta za police", desc: "Ad-Lite LED rasvjeta za isticanje asortimana na polici." },
  // Kolica
  { title: "Korpa Mini 80L", desc: "Kompaktna ručna korpa za brzu kupovinu, dostupna u više boja." },
  { title: "Korpa Mini 90L", desc: "Nešto veća ručna korpa sa ergonomskom drškom, više varijanti." },
  { title: "Korpa Samba 130L", desc: "Prostrana korpa Samba serije, izbor boja i Glamour linija." },
  { title: "Korpa Midi 160L", desc: "Veći kapacitet za objekte sa većom kupovinom po posjeti." },
  { title: "Korpa Maxi 210L", desc: "Najveća ručna korpa za supermarkete i hiper formate." },
  { title: "Korpa Panaro", desc: "Dizajnerska PANARO korpa s estetskim izgledom i bojom brenda." },
  { title: "Korpa PET Basket", desc: "Korpa od recikliranog PET materijala — eko opcija u brend boji." },
  { title: "Korpa Twinst", desc: "Twinst korpa sa inovativnim dizajnom za moderne objekte." },
  { title: "Avant 80", desc: "Kompaktna Avant kolica za convenience i mini supermarkete." },
  { title: "Avant 106", desc: "Standardna Avant kolica za supermarkete — ergonomska i čvrsta." },
  { title: "Avant 130", desc: "Avant 130 — najpopularniji model u seriji, idealan za prosječnu kupovinu." },
  { title: "Avant 185", desc: "Avant 185 za veće kupovine i hiper formate." },
  { title: "Avant 210", desc: "Najveći Avant model za visok kapacitet i bulk shopping." },
  { title: "Classic serija", desc: "Žičana Classic kolica — izdržljiva i ekonomična opcija." },
  { title: "Dječja kolica Kid Car", desc: "Kid Car kolica sa kabinom za djecu — više oblika i boja." },
  { title: "Kolica pristupačna (invalidska)", desc: "Pristupačna kolica za kupce smanjene pokretljivosti." },
  { title: "Transportna kolica Vario", desc: "Višenamjenska Vario transportna kolica za logistiku." },
  // Inox
  { title: "Inox radni stolovi i pultovi", desc: "Radne površine i pultovi od AISI inoxa, otporni na vlagu i intenzivan rad." },
  { title: "Sudopere i umivaonici", desc: "Jedno- i dvodjelne sudopere te higijenski umivaonici sa slavinama na koljeno." },
  { title: "Inox police", desc: "Zidne i samostojeće inox police za organizaciju radnog prostora." },
  { title: "Nape i ventilacija", desc: "Zidne i krovne inox nape za odvod pare i dima, sa filterima." },
  { title: "Zidni ormarići i elementi", desc: "Zidni inox ormarići za odlaganje pribora i namirnica." },
  { title: "Kante za otpad", desc: "Pedalne i ručne inox kante za higijensko upravljanje otpadom." },
  { title: "Kolica za serviranje", desc: "Mobilna inox kolica za serviranje i transport hrane." },
  { title: "Inox oprema po mjeri", desc: "Izrada inox opreme po mjeri prostora i radnih procesa." },
  { title: "Panjevi za meso", desc: "Drveni i polietilenski panjevi za sjeckanje mesa po HACCP normama." },
  { title: "Konvekcijske rerne", desc: "Profesionalne konvekcijske rerne za pekare, kuhinje i kafiće." },
  { title: "Kombi rerne", desc: "Parno-konvekcijske kombi rerne — precizan nadzor za profesionalne kuhinje." },
  { title: "Pizza peći", desc: "Profesionalne električne pizza peći sa kamenom za savršen rezultat." },
  { title: "Mini pizza peć", desc: "Kompaktna pizza peć za manje formate i kafiće." },
  { title: "Električne friteze", desc: "Električne friteze za profesionalnu pripremu pržene hrane." },
  { title: "Roštilji i grilovi", desc: "Električni i plin roštilji za profesionalnu pripremu mesa i ribe." },
  { title: "Roštilj na ćumur", desc: "Roštilj na ćumur za autentičan okus — profesionalna izvedba." },
  { title: "Bain-marie", desc: "Topla linija bain-marie za održavanje temperature jela." },
  { title: "Hot dog aparati", desc: "Aparati za rotaciono kuhanje kobasica i hot dog-a." },
  { title: "Toasteri", desc: "Profesionalni toasteri za brzu pripremu tostiranog kruha." },
  { title: "Vok ploče", desc: "Profesionalne vok ploče na gas za azijsku kuhinju." },
  { title: "Mikrotalasne peći", desc: "Profesionalne mikrotalasne za brzo zagrijavanje u HoReCa." },
  { title: "Brze rerne", desc: "Impingement rerne za brzo i ravnomjerno pečenje bez kompromisa." },
  { title: "Pizza pekači", desc: "Aluminijumi i čelični pizza pekači za komercijalnu upotrebu." },
  { title: "Sprave za pljeskavice", desc: "Aparati za formiranje pljeskavica — ručni i električni." },
  { title: "Mesoreznice", desc: "Električne mesoreznice sa podesivom debljinom reza." },
  { title: "Mlinovi za meso", desc: "Električni mlinovi za meso za intenzivan svakodnevni rad." },
  { title: "Mješalice za tijesto", desc: "Spiralne mješalice za tijesto — standardni i pojačani kapaciteti." },
  { title: "Kuhinjski i štapni mikseri", desc: "Profesionalni mikseri i potapajući štapni blenderi." },
  { title: "Rezači povrća", desc: "Električni rezači povrća za brzu i uniformnu pripremu." },
  { title: "Ljuštioci krompira", desc: "Električni ljuštioci krompira za HoReCa i veliku potrošnju." },
  { title: "Robot Coupe procesori", desc: "Robot Coupe food procesori — standard profesionalne kuhinje." },
  { title: "Vakuum aparati", desc: "Vakuum aparati za pakovanje i produženje roka trajanja." },
  { title: "Blenderi i sokovnici", desc: "Profesionalni blenderi i štapni blenderi za kuhinje i barove." },
  { title: "Sokovnici", desc: "Sokovnici za svježe cijeđene sokove — od citrus do centrifuge." },
  { title: "Sous Vide aparati", desc: "Sous vide cirkulatori za precizno kuhanje na niskim temperaturama." },
  { title: "Espresso aparati", desc: "Profesionalni espresso aparati za kafiće i restorane." },
  { title: "Automatski aparati za kafu", desc: "Automatski aparati sa touchscreen-om za kafu bez kompromisa." },
  { title: "Mlinovi za kafu", desc: "Profesionalni mlinovi za svježe mljevenu kafu." },
  { title: "Aparati za mlijeko i napitke", desc: "Aparati za topljenje i pripreme mlijeka i mliječnih napitaka." },
  { title: "Dispenzeri za napitke", desc: "Dispenzeri za vodu, sok i napitke — toplo i hladno." },
  { title: "Aparati za vafle", desc: "Profesionalni aparati za vafle za kafiće i poslastičarnice." },
  { title: "Mašine za pranje posuđa", desc: "Podpultne i haube mašine za pranje posuđa u HoReCa." },
  { title: "Mašine za pranje čaša", desc: "Kompaktne mašine specijalizovane za brzo pranje čaša." },
  { title: "Mašine sa haubicom", desc: "Hauba mašine visokog kapaciteta za intenzivne kuhinje." },
  { title: "Mašine za pranje pribora", desc: "Mašine za pranje kuhinjskog pribora i utensila." },
  { title: "GN posude i poklopci", desc: "Inox GN posude svih frakcija sa odgovarajućim poklopcima." },
  { title: "Posude za serviranje", desc: "Inox posude za serviranje jela u kantinama i restoranima." },
  { title: "Lonci i tiganji", desc: "Profesionalni inox lonci i tiganji za komercijalnu upotrebu." },
  { title: "Servirne linije za kantinu", desc: "Modularne toplo/hladne servirne linije za kantine." },
  { title: "Kuhinjska vaga", desc: "Precizne kuhinjske vage za profesionalnu upotrebu." },
  // Usmjeravanje
  { title: "Elektronski ulaz Porta'e Infra", desc: "Elektronska ulazna barijera sa infracrvenim senzorom — automatska i tiha." },
  { title: "Elektronski ulaz Porta'e Radar", desc: "Elektronska barijera sa radarskim detektorom kretanja za nesmetан prolaz." },
  { title: "Mehanički ulaz Porta M1", desc: "Mehanička jednosmjerna ulazna barijera — robusna i bez napajanja." },
  { title: "Barijera za kasu Porta C2", desc: "Barijera za zonu naplate koja usmjerava kupce i sprečava prolaz." },
  { title: "Barijere sa katancem", desc: "Mehaničke barijere sa integrisanom bravom za zaštitu zone naplate." },
  { title: "Vertikalni turniket", desc: "Vertikalni turniket za kontrolisan jednosmjerni pristup." },
  { title: "AlphaGate", desc: "ITAB AlphaGate — automatska ulazna kapija za moderne supermarkete." },
  { title: "SigmaGate", desc: "ITAB SigmaGate — kompaktna automatska kapija za uže ulaze." },
  { title: "CentroGate", desc: "ITAB CentroGate — srednje dimenzije za standardne ulaze." },
  { title: "ExitFlow", desc: "ITAB ExitFlow — jednosmjerni izlaz koji sprečava ulaz." },
  { title: "Sesame kapije", desc: "ITAB Sesame — kompaktne polautomatske kapije za uža mjesta." },
  { title: "Mehaničke kapije", desc: "Čelične mehaničke kapije za robusne zahtjeve." },
  { title: "ScanMaster", desc: "ITAB ScanMaster — kiosk za self-scan shopping u prodavnici." },
  { title: "Checkout Closer", desc: "ITAB Checkout Closer — fleksibilno zatvaranje kasa za urednu zonu." },
  { title: "Barijere i pregrade ITAB", desc: "ITAB barijere i pregrade za usmjeravanje i zaštitu zone naplate." },
];

async function main() {
  for (const { title, desc } of descs) {
    const r = await prisma.product.updateMany({ where: { title }, data: { description: desc } });
    if (r.count > 0) process.stdout.write(".");
  }
  console.log(`\n✅ ${descs.length} descriptions updated`);
}

main().catch(console.error).finally(() => prisma.$disconnect());
